act-rules/act-rules-web

build/get-wcag-meta-data.js, package.json
- refactor the fn to take in args via CLI
=> refactor: update fn getWcagMetaData

.gitignore, build/create-testcases.js, build/testcases/create-testcases-json.js, build/testcases/create-testcases-of-rule-of-em-report-tool.js, gatsby-config.js, package-lock.json, package.json, src/components/footer/index.js, src/components/layout/index.js, src/components/seo.js, src/pages/glossary.js, src/pages/rules.js, src/templates/changelog.js, src/templates/default.js, src/templates/glossary.js, src/templates/implementations.js, src/templates/implementer.js, src/templates/rule.js, yarn.lock
- update build scripts
- update references to package.json from act-rules community
- get `build` to succeed
=> refactor: update website code to take `act-rules-community` as dependency

src/components/layout/index.scss, src/templates/rule.js
Issue #31 adjusted the markup and styling to prevent overlapping scroll areas for table of contents and rule content.
=> fix: keyboard trap and styling changes for scroll areas

build/testcases/create-testcases-json.js, src/components/seo.js
- resolve author name correctly
- resolve author name in website title
=> fix: broken files in testcases.json

build/earl-context.json
=> fix(earl-context): dct:title was incorrect

src/components/acknowledgements.js, src/templates/rule.js, src/utils/render-fragments.js
Addresses Issue #35 
Not completely sure if this is how you want to handle this issue. Was trying to come up with a non-breaking change that can accommodate what is out there currently and reuse the existing function. Open to suggestions. Also unsure about how to tell graphQL I added a new field to pass the build here.
If this works will need to add corresponding previous_authors to rules repo rule templates.
=> feat: add Acknowledgements component to render in Rule page

src/components/list-with-heading.js, src/pages/glossary.js, src/utils/render-fragments.js
- added a helper component for rending list(s) and list items with a heading
- update glossary component to a functional component
=> refactor: update `glossary` component

src/components/layout.scss, src/components/rule-card.js, src/components/rule-card.scss, src/pages/rules.js, src/pages/rules.scss, src/styles/mixins.scss
- create a `rule card` component.
- this helps abstraction for easier maintenance in the long run.
=> refactor: `RuleCard` component for items rendered in `rules` page

src/components/seo.js
=> fix: add default `lang="en"` attribute

src/components/layout.scss, src/components/rule-table-of-contents.js, src/components/rule-table-of-contents.scss, src/templates/rule.js, src/utils/render-fragments.js
As described. Refactor for easier maintenance.
=> refactor: component(ise) rule's table of contents 

src/components/table-testcase-findings.js, src/styles/base.scss, src/styles/mixins.scss, src/templates/implementer-incomplete.js
- The page was not scrollable to see all the data correctly.
- This PR fixes various layout issues with the incomplete implementations page.
=> fix: layout of tables in incomplete implementations page

src/components/layout.js, src/templates/rule.js, utils/curate-git-url.js
=> fix: GitHub redirect link from GitHub logo on the website

build/create-testcases.js, utils/reg-exps.js
Needed for https://github.com/act-rules/act-rules.github.io/pull/1073
=> Handle XHTML test cases

gatsby-config.js, package.json, plugins/swap-heading-level/index.js, plugins/swap-heading-level/package-lock.json, plugins/swap-heading-level/package.json
Closes Issue: 
- https://github.com/act-rules/act-rules-web/issues/20
=> fix: glossary heading depth during page generation

package-lock.json, package.json, src/components/rules-filter.js, src/components/rules-filter.scss, src/pages/rules.js, src/pages/rules.scss, src/styles/mixins.scss
Enable text based fuzzy search on the rules page. This will allow to filter using id, name, description or rule type.
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/24
=> feat: filtering in rules page

src/components/rules-filter.js, src/pages/rules.js
- this is a quick fix to the filtering options in rules page, where the rules were not repopulated correctly after a filter was cleared.
=> fix: clear filter when input is empty

package-lock.json, src/components/layout.js, src/pages/rules.js, src/pages/rules.scss, src/styles/mixins.scss
Fixes layout across multiple components, to manage responsiveness for smaller viewport sizes and in zoom in situations.
=> fix: responsive layout on smaller viewport size or when zoomed in

src/components/note.scss
=> fix: update NOTE component for color contrast

build/create-glossary-usages.js, build/create-implementation-metrics.js, build/create-rules-usages.js, build/create-testcases.js, build/get-implementations.js, build/get-wcag-meta-data.js
Ran into a build error, which did not exit correctly
=> chore: exit node process correctly

package-lock.json, package.json, src/templates/implementer-incomplete.js, src/templates/implementer.js
- show consistency of a mapping on each of the implementations
=> fix: add consistency to implementation report

gatsby-node.js
Need to come up with a different solution for creating testcases as zip files.
Reverting the change to zipping testcases.
=> chore (revert): generating `testcases.zip`

src/components/count-implementations.js
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/127
=> fix: update to count only complete implementations in rules page

src/components/list-of-implementers.js, src/styles/base.scss, src/templates/rule.js
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/126
Implementations table shown in a rule page: 
Implementations table shown as overview:
=> fix: update list of implementations with more data

src/components/acknowledgements.js
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/113
=> fix: lose underscore in acknowledgements key's if any

src/components/footer.js
Make the link to WAI tools actually link to WAI tools
=> Correct link to WAI tools

implementations.yml
Once this PR is merged - https://github.com/act-rules/act-rules-implementation-access-engine/pull/1
This update needs to land to enable resolving to the new report provided by level access.
=> refactor: update implementation report path for level access

src/components/accessibility_requirements/index.js
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/149
=> fix: update outcome mapping sentence

src/templates/rule.js
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/141
=> fix: add disclaimer before implementations table in rule page

src/components/layout.scss
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/146
=> fix: set background for `main` content

package-lock.json, src/components/accessibility_requirements/index.js, src/templates/implementer-incomplete.js, src/templates/rule.js, src/utils/render-fragments.js
There were small disparities in the UI of the rule page, like shown in the screenshot below:
--- 
This PR fixes them:
=> fix: clean up rule page layout

build/create-glossary-usages.js, build/create-implementation-metrics.js, build/create-rules-usages.js, build/create-testcases.js, build/get-implementations.js, build/get-wcag-meta-data.js
Got a random error when `npm run getData` within this repo:
=> refactor: add `then` to promise chaining over `finally`

gatsby-config.js, plugins/rule-example-open-in-new-tab/index.js, plugins/rule-example-open-in-new-tab/package-lock.json, plugins/rule-example-open-in-new-tab/package.json, src/templates/rule.scss
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/39
=> feat: allow test case example(s) to be opened from a new tab

.github/workflows/publish.yml
This change means that testcases & the test-assets that have changed overtime will be persisted.
=> chore: persist testcases and test assets

src/pages/404.js, src/styles/mixins.scss
Closes:
- https://github.com/act-rules/act-rules-web/issues/185
=> fix: update styles and content of 404 page

src/templates/rule.js
Closes:
- https://github.com/act-rules/act-rules-web/issues/184
=> fix: ensure links are relative for used in rules

src/components/acknowledgments.js
Noticed that rendering of acknowledgements should only render links when it is authors/ previous authors.
=> fix: update rendering of acknowledgements

src/components/list-of-implementers.js
Closes:
- https://github.com/act-rules/act-rules-web/issues/211
=> fix: spelling typo in iplementation table heading

src/components/rule-card.scss, src/templates/rule.scss
Closes:
- https://github.com/act-rules/act-rules-web/issues/212
=> fix: color contrast issue on links

gatsby-node.js
Simple qualtiy-of-life improvement to using the repo as an NPM module.
=> feat: set main: testcases.json in public/package.json

src/components/navigation.js
No need to merge this before https://github.com/act-rules/act-rules.github.io/pull/1774
=> Enabled sorting of menu items that have the order frontmatter
