src/components/layout/index.scss, src/pages/rules.js, src/styles/mixins.scss, src/templates/rule.js
This PR resolves back ticks on headings of rules.
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/17
=> fix: rule headings should resolve back ticks

src/components/navigation.js
On larger zoom levels, the side menu bar is collapsed, therefore allowing the main content to be scrollable (both horizontally & vertically).
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/50
=> fix: allow horizontal scrolling on higher zoom levels

package-lock.json, package.json
Given [act-implementation-mapper](https://github.com/act-rules/act-rules-implementation-mapper) has matured & the current website code adaptation has not been merged yet, see PR https://github.com/act-rules/act-rules-web/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
It makes sense to fix the `act-implementation-mapper` to a specific [version](https://github.com/act-rules/act-rules-implementation-mapper/commit/b8562dfa8adb3c44ec005d253dfa6548196f81cd), to allow for passing builds
=> fix: freeze act-map-generator to old version

src/styles/mixins.scss
While it's true that most elements that use this mixin are also interactive, it is also used on static elements ... and here, having the explicit `cursor:pointer` mouse cursor (the "hand" one) is misleading and confusing, as it makes those static elements appear to be interactive/clickable to sighted mouse users.
Closes #54
Closes #69
=> fix: Remove cursor:pointer from header-style mixin

gatsby/create-page-implementer-report.js, manual-rules.yml, src/templates/implementer-incomplete.js
It is not essential to keep a list of manual rules in the website.
Closes:
- https://github.com/act-rules/act-rules-web/issues/99
=> fix: remove listing of manual rules

build/get-wcag-meta-data.js
URLS referring to WCAG should resolve to WCAG21 over WCAG20.
Closes: 
- https://github.com/act-rules/act-rules-web/issues/42
=> fix: urls for SC should resolve to WCAG21 references

src/components/list-of-implementations.js, src/templates/implementer-incomplete.js, src/templates/implementer.js
Rules that do not map to WCAG (Eg: ARIA rules) and those that are not required for conformance should not be a part of complete implementations page, unless an implementation mapping exists for them.
=> fix: do not show non wcag or not for conformance rules as complete

package-lock.json, package.json, utils/get-markdown-data.js
Apparently using `remark.parse` converted some of the frontmatter content to markdown AST in terms of computed some frontmatter as body content, and swapping to use using unified and specifying to treat frontmatter as its own content does the trick.
=> fix: use unified to ensure markdownAST is computed correctly

.github/workflows/test.yml
It looks like this never worked & this is not built to work for SPA. 
This is not what we intend to test for broken links. A better solution needs to be found.
=> test: remove linkinator which verifies for broken links

build/create-testcases.js, build/testcases/create-testcases-json.js, build/testcases/create-testcases-of-rule-of-em-report-tool.js, gatsby-node.js, implementations.yml, package-lock.json, package.json, utils/create-zip.js
Zip all testcases html files along with their assets. This will allow for the various implementers to have easier access to them, than just the testcases.json.
> Note: Need to update documentation and add a link to download this zip (this will happen in a different repo).
=> chore: create a zip of testcases and its assets

.gitattributes
In attempting to zip and upload testcases as a zip, which is a fairly large file, git did not allow to push.
See here for logs:
https://github.com/act-rules/act-rules-web/runs/417639910?check_suite_focus=true
I followed docs here, https://git-lfs.github.com/ and this hopefully this should allow to push/ track large files.
=> chore: add git lfs support to track large files

implementations.yml, package-lock.json, package.json
Here's a PR to add our implementation report to the ACT Rules website.
npm install made some changes to package-lock.json (updated some requires versions and added an axe dependency) that didn't look relevant so they're not in the PR
=> chore: added implementation wire-up for sortsite

src/components/acknowledgments.js, src/components/rule-table-of-contents.js, src/templates/rule.js
Allow for acknowledgement component to parse either `acknowledgements` or `acknowledgments` from frontmatter. The key change is here - https://github.com/act-rules/act-rules-web/pull/143/files#diff-be21b5bf63b1baeff8443e1bfcc6b40dR152
> Note: I renamed the component for consistency purposes & verified locally.
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/142
=> fix: update `acknowledgment` component

src/pages/rules.js
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/138
> Screenshot showing that names with backticks are alphabetically sorted along with other names.
=> fix: sort rules in website alphabetically (ignoring backticks & casing)

src/components/list-of-implementers.js
The table must be sorted like so:
- consistent before partially consistent
- complete before incomplete
Closes Issue:
- https://github.com/act-rules/act-rules-web/issues/126
=> fix: sort implementations table as per below logic

src/components/header.scss
Removed some overriding styles for an anchor element that was affecting the color contrast
Fix color contrast:
=> fix: color contrast issue on header title anchor

src/templates/rule.scss
Given the open in a new tab (for example) was introduced. The margin between example description and example title was increased. This fix reduces that.
=> fix: reduce size between example heading and content

src/components/list-with-heading.js, src/pages/glossary.js, src/pages/glossary.scss, src/templates/rule.js, src/templates/rule.scss, src/utils/render-fragments.js
Decided to reuse a generic component `ListWithHeading` & refactor accordingly.
=> fix: ensure markdown backticks are parsed as html for used in rules

src/pages/glossary.js, src/utils/render-fragments.js
Closes:
- https://github.com/act-rules/act-rules-web/issues/167
=> fix: remove glossary `key` from rendered pages

.github/workflows/publish.yml
Shell `mv` command did not allow for overwrites and hence failing the build like here - https://github.com/act-rules/act-rules-web/runs/693547999?check_suite_focus=true
Using `cp` allows for overwrite.
=> fix: publish website script

plugins/rule-example-open-in-new-tab/index.js
Adding `target='_blank'` to open example in a new tab rather than current tab
=> fix: open example in new tab

src/templates/rule.js
This change gets rid of the below section for rules that are not used in other rules.
=> fix: update rule template to not show `used in rules` metadata when there are none.

plugins/rule-example-open-in-new-tab/index.js
Sadly this PR - https://github.com/act-rules/act-rules-web/pull/174, added the open in a new tab `target='_blank'` to a different anchor element.
This PR fixes that.
=> fix: open example in a new tab

.github/workflows/publish.yml, .github/workflows/test.yml
Updating to v2 version of `actions/checkout@v2` - See [whats new](https://github.com/actions/checkout#whats-new)
Closes issue(s):
- NA
=> chore: update checkout action to v2

build/create-testcases.js
Closes:
- https://github.com/act-rules/act-rules-web/issues/183
=> fix: ensure `DOCTYPE` is not appended if it already exists

src/components/accessibility_requirements/index.js
Allow to link to any anchor in WCAG text.
Notably to non interference requirement with:
```
wcag-text:cc5:
title: WCAG Non-Interference
forConformance: true
failed: not satisfied
passed: further testing needed
inapplicable: further testing needed
```
=> Handle link to the text of WCAG, not just a SC

src/components/navigation.js
The `examples` directory in `pages` were dynamically computed to be added to the menu structure, resulting in:
This fix, filters examples directory from being shown in navigation, but still allowing the relevant pages to be generated.
=> fix: exclude examples of glossary from navigation

src/rule/get-accessibility-requirement.js
* Missing `#` in an URL.
* Global WCAG requirement (i.e. "non-interference") were listed in rules as "not required for conformance".
=> Fix base URL + add conformance statement for global WCAG requirements

src/components/glossary.js, src/components/glossary.scss
Removing some styles as requested by @WilcoFiers 
Preview:
=> style: remove background for glossary in rule page

gatsby-node.js
Add a package.json to the /public directory, so that the #master branch can be installed using NPM (with no dependencies).
=> feat: add package.json to public

build/earl-context.json
`title` should have just been a short hand for `dct:title`, rather than having it as a type. `dct:title` is a property, not a class.
=> Fix dct:title in earl-context.json

implementations.yml
The IBM engine now generates the earl results as part of the build, available via JSDelivr/NPM. Rule architecture modified slightly, hence change of description.
=> Update implementations.yml for IBM
